export enum SearchProviderId {
	MOCK = "mock",
	EXAMPLE = "example",
}

export enum ProviderCapability {
	DISJUNCTIVE_FACETING = "DISJUNCTIVE_FACETING",
	VECTOR_HYBRID_SEARCH = "VECTOR_HYBRID_SEARCH",
	HIERARCHICAL_FACETS = "HIERARCHICAL_FACETS",
	QUERY_SUGGESTIONS = "QUERY_SUGGESTIONS",
	DYNAMIC_BOOSTING = "DYNAMIC_BOOSTING",
	SYNONYM_EXPANSION = "SYNONYM_EXPANSION",
	GEO_FILTERING = "GEO_FILTERING",
}
